// GENERATED FILE — DO NOT EDIT MANUALLY
//
// This file is generated by `flutterfire configure`.
//
// Steps to generate:
//   1. Install FlutterFire CLI:  dart pub global activate flutterfire_cli
//   2. Run: flutterfire configure
//   3. Select your Firebase project and platforms (Android).
//   4. The real firebase_options.dart will be generated automatically.
//
// Until you run `flutterfire configure`, the app will initialise Firebase
// without a DefaultFirebaseOptions object and rely on google-services.json
// for Android configuration (which is sufficient for most use cases).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Replace the placeholder values below with the values from your
/// Firebase project's google-services.json / GoogleService-Info.plist.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web. '
        'Reconfigure using the FlutterFire CLI.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform: '
          '$defaultTargetPlatform. '
          'Reconfigure using the FlutterFire CLI.',
        );
    }
  }

  // ---------------------------------------------------------------------------
  // Replace the placeholder values below with values from your
  // Firebase project: google-services.json → client[0]
  // ---------------------------------------------------------------------------
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_ANDROID_API_KEY',
    appId: '1:000000000000:android:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'gardnx-app',
    storageBucket: 'gardnx-app.appspot.com',
  );
}
